version: "1"

services:
  mongoDB:
    image: mongo
    restart: always
    container_name: mongoTasker
    environment:
      MONGO_INITDB_ROOT_USERNAME: karamjeet
      MONGO_INITDB_ROOT_PASSWORD: Karam5566
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongoExpress
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: karamjeet
      ME_CONFIG_MONGODB_ADMINPASSWORD: Karam5566
      ME_CONFIG_MONGODB_URL: mongodb://karamjeet:Karam5566@mongoDB:27017/
    depends_on:
      - mongoDB

volumes:
  mongo_data:
